apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jl4k1a226-nodejs
  janus-idp.io/tekton: jl4k1a226-nodejs
  backstage.io/kubernetes-id: jl4k1a226-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jl4k1a226-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
