apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jl4k1a226-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jl4k1a226-nodejs 
  name: jl4k1a226-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jl4k1a226-nodejs 
